name: morning-traffic-check
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  traffic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: check and notify
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: python3 check_traffic.py
